spring:
  application:
    name: kost-api

  datasource:
    url: jdbc:postgresql://localhost:5432/kost_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: secret
  expiration: 86400000